
name: Genesys Cloud Failure IVR Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-flow:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: "prod-ivr"
    steps:
      - uses: actions/checkout@v2   
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_IVR_TOKEN }}
      - run: |
          cd blueprint/terraform-ivr
          terraform init 
          terraform apply --auto-approve

      