
name: Genesys Cloud IVR Export and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  export-and-deploy-flow:
    runs-on: ubuntu-latest
    env:
      GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID_PROD }}
      GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET_PROD }}
      GENESYSCLOUD_REGION: "us-west-2"
      TF_WORKSPACE: "prod-ivr"
    steps:
      - uses: actions/checkout@v2   
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_IVR_TOKEN }}
      - run: |
          cd blueprint/terraform-ivr
          terraform init 
          terraform apply --auto-approve

      